config/routes.rb
Toauction::Application.routes.draw do
  get "admin/index"

  resources :bids

  resources :products

  get "store/index"

  devise_for :users
  resources :users

  root :to => 'store#index'

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  attr_accessible :product_id, :user_id
  belongs_to :product
  belongs_to :user
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bids }
    end
    #authorize! :manage, @bids
    authorize! :manage, @bids
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
    @bid = Bid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bid }
    end
    authorize! :manage, @bid
  end

  # GET /bids/new
  # GET /bids/new.json
  def new
    @bid = Bid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bid }
    end
    authorize! :manage, @bid
  end

  # GET /bids/1/edit
  def edit
    @bid = Bid.find(params[:id])
    authorize! :manage, @bid
  end

  # POST /bids
  # POST /bids.json
  def create
    @user = current_user
    @product = Product.find(params[:product_id])
    @bid = @user.bids.build
    @product.high_bidder = @user.id
    @bid.product = @product
    @product.current_price = @product.current_price + @product.current_price * 0.1
    @product.save
    
    #implement later for time controlled bids
    #if @product.end_time - Time.now > 0
    #
    #send

    respond_to do |format|
      if @bid.save
        
        format.html { redirect_to :back, notice: 'Bid was successfully created.' }
        format.json { render json: @bid, status: :created, location: @bid }
      else
        format.html { render action: "new" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PUT /bids/1
  # PUT /bids/1.json
  def update
    @bid = Bid.find(params[:id])

    respond_to do |format|
      if @bid.update_attributes(params[:bid])
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
    authorize! :manage, @bid
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid = Bid.find(params[:id])
    @bid.destroy

    respond_to do |format|
      format.html { redirect_to bids_url }
      format.json { head :no_content }
    end
  end
  authorize! :manage, @bid
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% @bid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing bid</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<h1>Listing bids</h1>
<table>
  <tr>
    <th>Product</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bids.each do |bid| %>
  <tr>
    <td><%= bid.product_id %></td>
    <td><%= bid.user_id %></td>
    <td><%= link_to 'Show', bid %></td>
    <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
    <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bid', new_bid_path %>

app/views/bids/new.html.erb
<h1>New bid</h1>

<%= render 'form' %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @bid.product_id %>
</p>

<p>
  <b>User:</b>
  <%= @bid.user_id %>
</p>


<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>